HADOOP-7325. The hadoop command should not accept class names starting with a hyphen. Contributed by Brock Noland.
git-svn-id: https://svn.apache.org/repos/asf/hadoop/common/branches/branch-0.22@1132768 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/hadoop b/bin/hadoop
--- a/bin/hadoop
+++ b/bin/hadoop
@@ -108,6 +108,10 @@ case $COMMAND in
       CLASS=org.apache.hadoop.tools.HadoopArchives
       CLASSPATH=${CLASSPATH}:${TOOL_PATH}
       HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
+    elif [[ "$COMMAND" = -*  ]] ; then
+        # class and package names cannot begin with a -
+        echo "Error: No command named \`$COMMAND' was found. Perhaps you meant \`hadoop ${COMMAND#-}'"
+        exit 1
     else
       CLASS=$COMMAND
     fi
