Reverting change 399426, which broke distributed operation.
git-svn-id: https://svn.apache.org/repos/asf/lucene/hadoop/trunk@399461 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/hadoop b/bin/hadoop
--- a/bin/hadoop
+++ b/bin/hadoop
@@ -135,7 +135,14 @@ elif [ "$COMMAND" = "tasktracker" ] ; then
 elif [ "$COMMAND" = "job" ] ; then
   CLASS=org.apache.hadoop.mapred.JobClient
 elif [ "$COMMAND" = "jar" ] ; then
-  CLASS=org.apache.hadoop.util.RunJar
+  JAR="$1"
+  shift
+  CLASS=`"$0" org.apache.hadoop.util.PrintJarMainClass "$JAR"`
+  if [ $? != 0 ]; then
+    echo "Error: Could not find main class in jar file $JAR"
+    exit 1
+  fi
+  CLASSPATH=${CLASSPATH}:${JAR}
 else
   CLASS=$COMMAND
 fi
