HADOOP-2410.  Make EC2 cluster nodes more independent of each other.  Contributed by Chris K Wensel.
git-svn-id: https://svn.apache.org/repos/asf/hadoop/core/trunk@644712 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/contrib/ec2/bin/destroy-hadoop-cluster b/src/contrib/ec2/bin/destroy-hadoop-cluster
--- a/src/contrib/ec2/bin/destroy-hadoop-cluster
+++ b/src/contrib/ec2/bin/destroy-hadoop-cluster
@@ -15,21 +15,34 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+# Launch an EC2 cluster of Hadoop instances.
 
-# Launch an EC2 cluster of Hadoop instances, start Hadoop, and connect to the master.
+if [ -z $1 ]; then
+  echo "Cluster name required!"
+  exit -1
+fi
+
+CLUSTER=$1
 
 # Import variables
 bin=`dirname "$0"`
 bin=`cd "$bin"; pwd`
+. "$bin"/hadoop-ec2-env.sh
 
-if ! "$bin"/launch-hadoop-cluster ; then
-  exit $?
+rm -f $MASTER_IP_PATH
+rm -f $MASTER_PRIVATE_IP_PATH
+
+ec2-describe-group | egrep "[[:space:]]$CLUSTER_MASTER[[:space:]]" > /dev/null
+if [ $? -eq 0 ]; then
+  echo "Destroying group $CLUSTER_MASTER"
+  ec2-revoke $CLUSTER_MASTER -o $CLUSTER -u $AWS_ACCOUNT_ID
 fi
 
-echo "Press return to continue."
-read dummy
+ec2-describe-group | egrep "[[:space:]]$CLUSTER[[:space:]]" > /dev/null
+if [ $? -eq 0 ]; then
+  echo "Destroying group $CLUSTER"
+  ec2-revoke $CLUSTER -o $CLUSTER_MASTER -u $AWS_ACCOUNT_ID
+fi
 
-echo "Waiting before trying to connect..."
-sleep 30
-
-"$bin"/start-hadoop
+ec2-delete-group $CLUSTER_MASTER
+ec2-delete-group $CLUSTER
